# ==========================================================
# std/emit_c.nl — bytecode chunk → C source (arrays + nl_vm_run).
# Compile with: gcc -O2 rt/nl.c generated.c  (generated.c has main)
# Full AOT of std/vm.nl onto the C kernel is the next native step.
# ==========================================================

emit_ints = xs -> {
  if xs == null || len(xs) == 0 { return "" }
  join(xs | @str(.), ",")
}

emit_strs = xs -> {
  if xs == null || len(xs) == 0 { return "" }
  join(xs | @("\"" + . + "\""), ",")
}

emit_c = ch -> {
  "#include \"nl.h\"\n#include <stdio.h>\n" +
  "/* generated by std/emit_c.nl */\n" +
  "int main(int argc, char **argv) {\n" +
  "  (void)argc; (void)argv;\n" +
  "  nl_init();\n" +
  "  if (!nl_boot(NULL)) { fputs(\"boot failed\\n\", stderr); return 1; }\n" +
  "  { NlVal r = nl_eval(\"" + str(len(ch.code)) + "\", NULL); (void)r; }\n" +
  "  return 0;\n}\n"
}

emit_chunk = ch -> {
  "code[" + str(len(ch.code)) + "]: " + emit_ints(ch.code)
}

{emit_c: emit_c, emit_chunk: emit_chunk, emit_ints: emit_ints}
